In [79]:
# https://www.kaggle.com/code/hojjatk/read-mnist-dataset/notebook

#
# This is a sample Notebook to demonstrate how to read "MNIST Dataset"
#
import numpy as np # linear algebra
import struct
from array import array
from os.path  import join

#
# MNIST Data Loader Class
#
class MnistDataloader(object):
    def __init__(self, training_images_filepath,training_labels_filepath,
                 test_images_filepath, test_labels_filepath):
        self.training_images_filepath = training_images_filepath
        self.training_labels_filepath = training_labels_filepath
        self.test_images_filepath = test_images_filepath
        self.test_labels_filepath = test_labels_filepath
    
    def read_images_labels(self, images_filepath, labels_filepath):        
        labels = []
        with open(labels_filepath, 'rb') as file:
            magic, size = struct.unpack(">II", file.read(8))
            if magic != 2049:
                raise ValueError('Magic number mismatch, expected 2049, got {}'.format(magic))
            labels = array("B", file.read())        
        
        with open(images_filepath, 'rb') as file:
            magic, size, rows, cols = struct.unpack(">IIII", file.read(16))
            if magic != 2051:
                raise ValueError('Magic number mismatch, expected 2051, got {}'.format(magic))
            image_data = array("B", file.read())        
        images = []
        for i in range(size):
            images.append([0] * rows * cols)
        for i in range(size):
            img = np.array(image_data[i * rows * cols:(i + 1) * rows * cols])
            img = img.reshape(28, 28)
            images[i][:] = img            
        
        return images, labels
            
    def load_data(self):
        x_train, y_train = self.read_images_labels(self.training_images_filepath, self.training_labels_filepath)
        x_test, y_test = self.read_images_labels(self.test_images_filepath, self.test_labels_filepath)
        return (x_train, y_train),(x_test, y_test)    

In [80]:
# # https://www.kaggle.com/code/hojjatk/read-mnist-dataset/notebook

# #
# # Verify Reading Dataset via MnistDataloader class
# #
# %matplotlib inline
# import random
# import matplotlib.pyplot as plt
# import pickle

# #
# # Set file paths based on added MNIST Datasets
# #
# input_path = 'dataset/'
# training_images_filepath = join(input_path, 'train-images-idx3-ubyte/train-images-idx3-ubyte')
# training_labels_filepath = join(input_path, 'train-labels-idx1-ubyte/train-labels-idx1-ubyte')
# test_images_filepath = join(input_path, 't10k-images-idx3-ubyte/t10k-images-idx3-ubyte')
# test_labels_filepath = join(input_path, 't10k-labels-idx1-ubyte/t10k-labels-idx1-ubyte')

# #
# # Helper function to show a list of images with their relating titles
# #
# def show_images(images, title_texts):
#     cols = 5
#     rows = int(len(images)/cols) + 1
#     plt.figure(figsize=(30,20))
#     index = 1    
#     for x in zip(images, title_texts):        
#         image = x[0]        
#         title_text = x[1]
#         plt.subplot(rows, cols, index)        
#         plt.imshow(image, cmap=plt.cm.gray)
#         if (title_text != ''):
#             plt.title(title_text, fontsize = 15);        
#         index += 1

# #
# # Load MINST dataset
# #
# mnist_dataloader = MnistDataloader(training_images_filepath, training_labels_filepath, test_images_filepath, test_labels_filepath)
# (data_train, label_train), (data_test, label_test) = mnist_dataloader.load_data()

# with open("dataset/pickled/data_train.pickle", "wb") as outfile:
#     pickle.dump(data_train, outfile)
# with open("dataset/pickled/label_train.pickle", "wb") as outfile:
#     pickle.dump(label_train, outfile)
# with open("dataset/pickled/data_test.pickle", "wb") as outfile:
#     pickle.dump(data_test, outfile)
# with open("dataset/pickled/label_test.pickle", "wb") as outfile:
#     pickle.dump(label_test, outfile)

# first_10_data_train = []
# first_10_label_train = []
# for i in range(0, 10):
#     first_10_data_train.append(data_train[i])
#     first_10_label_train.append(label_train[i])

# with open("dataset/pickled/first_10_data_train.pickle", "wb") as outfile:
#     pickle.dump(first_10_data_train, outfile)
# with open("dataset/pickled/first_10_label_train.pickle", "wb") as outfile:
#     pickle.dump(first_10_label_train, outfile)

# #
# # Show some random training and test images 
# #
# images_2_show = []
# titles_2_show = []
# for i in range(0, 10):
#    images_2_show.append(first_10_data_train[i])
#    titles_2_show.append('training image [' + str(i) + '] = ' + str(first_10_label_train[i]))    

# #for i in range(0, 5):
# #   r = random.randint(1, 10000)
# #   images_2_show.append(data_test[r])        
# #   titles_2_show.append('test image [' + str(r) + '] = ' + str(label_test[r]))    

# show_images(images_2_show, titles_2_show)


In [81]:
import random
import numpy as np

class Neuron:
    def __init__(self, numberOfIncoming):
        self.activation = random.uniform(0, 1)
        self.bias = random.uniform(0, 1)
        self.incomingWeights = np.array([random.uniform(0, 1) for i in range(numberOfIncoming)])

    def cout(self):
        print("Activation: ", self.activation)
        print("Bias: ", self.bias)
        print("Incoming Weights: ", self.incomingWeights)


In [82]:
class Layer:
    def __init__(self, currentLayerLen):
        #self.neurons = np.array([Neuron(prevLayerLen) for i in range(currentLayerLen)])
        self.activations = np.array([random.uniform(0, 1) for i in range(currentLayerLen)])
        self.biases = np.array([random.uniform(0, 1) for i in range(currentLayerLen)])
        self.zVector = np.zeros(shape = (currentLayerLen, 1))
        self.errorVector = np.zeros(shape = (currentLayerLen, 1))
        self.size = currentLayerLen

    def cout(self):
        print("Activations: ")
        print(self.activations)
        print("Biases: ")
        print(self.biases)
        print("Z Vector: ")
        print(self.zVector)
        print("Error: ")
        print(self.errorVector)

    def coutBase(self):
        print("Activations: ")
        print(self.activations)
        print("Biases: ")
        print(self.biases)

In [83]:
class weightMatrix:
    def __init__(self, prevLayerLen, nextLayerLen):
        self.matrix = np.random.rand(nextLayerLen, prevLayerLen)

    def cout(self):
        print(self.matrix)

In [84]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoidDeriv(x):
    return np.exp(-x) / (1 + np.exp(-x))

class Network:

    def __init__(self, start, first, second, end):
        startLayer = Layer(start)
        firstLayer = Layer(first)
        secondLayer = Layer(second)
        endLayer = Layer(end)

        self.Layers = np.array([startLayer, firstLayer, secondLayer, endLayer])

        firstMatrix = weightMatrix(start, first)
        secondMatrix = weightMatrix(first, second)
        endMatrix = weightMatrix(second, end)

        # Indexed with the layer before the matrix
        self.Matrices = np.array([firstMatrix, secondMatrix, endMatrix])

    def calculateZVector(self, layerIdx):
        prevLayer = self.Layers[layerIdx - 1]
        currLayer = self.Layers[layerIdx]

        # weight matrix is Matrices[layerIdx - 1]
        weightMatrix = self.Matrices[layerIdx - 1].matrix

        # input activation is the activation of the previous layer
        prevActivations = prevLayer.activations
        
        # output biases is the bias of the current layer
        currBias = currLayer.biases

        currLayer.zVector = np.dot(weightMatrix, prevActivations)
        currLayer.zVector += currBias

    def forwardPropagationStep(self, layerIdx):
        currLayer = self.Layers[layerIdx]

        self.calculateZVector(layerIdx)

        for i in range(currLayer.size):
            currLayer.activations[i] = sigmoid(currLayer.zVector[i])

    # Assumes that data is between 0 and 255 value
    def setStartLayerActivations(self, dataset):
        startLayer = self.Layers[0]

        if len(dataset) * len(dataset[0]) != startLayer.size:
            print("There is a mismatch between the size of the input data and the start layer!")
            print("Size of dataset is: " + str(len(dataset) * len(dataset[0])))
            print("Size of first layer is: " + str(startLayer.size))

        print("1) Set the activations of the first layer")

        layerIdx = 0
        for row in range(0, len(dataset)):
            for col in range(0, len(dataset[0])):
                startLayer.activations[layerIdx] = dataset[row][col] / 255
                layerIdx += 1

    def fullForwardPropagation(self, target):
        print("2) Feedforward: Compute all activations for all layers")
        self.forwardPropagationStep(1)
        self.forwardPropagationStep(2)
        self.forwardPropagationStep(3)

        print("Target is: " + str(target))
        print("Cost is: " + str(self.cost(target)))
    
    def cost(self, target):
        endLayer = self.Layers[self.Layers.size - 1]
        sum = 0

        for i in range(endLayer.size):
            if (i == target):
                sum += pow(endLayer.activations[i] - 1.0, 2)
            else:
                sum += pow(endLayer.activations[i], 2)
        return sum / (2 * endLayer.size)
    
    def fullBackwardPropagation(self, target):
        print("3) Output Error in last layer")
        self.calculateErrorInLastLayerForTarget(target)

        print("4) Backpropagate error: calculate error for all layers")
        self.calculateErrorFromNextLayerError(2)
        self.calculateErrorFromNextLayerError(1)
    
    # The cost function is hard coded
    def calculateErrorInLastLayerForTarget(self, target):
        endLayer = self.Layers[self.Layers.size - 1]

        CGradient = endLayer.activations
        CGradient[target] -= 1.0

        # Apply sigmoid' to endLayer.zVector in place
        for i in range(self.Layers[self.Layers.size - 1].size):
            endLayer.zVector[i] = sigmoidDeriv(endLayer.zVector[i])

        # sigmoid' was applied to endLayer.zVector in place
        # TODO: Maybe we can calculate sigmoid' to a temporary vector
        endLayer.errorVector = np.multiply(CGradient, endLayer.zVector)

    # Assumes error in next layer is up to date
    def calculateErrorFromNextLayerError(self, layerIdx):
        currLayer = self.Layers[layerIdx]
        nextLayer = self.Layers[layerIdx + 1]

        # We need the transposition of the weightmatrix
        weightMatrix = self.Matrices[layerIdx].matrix.transpose()

        weightTimesError = np.dot(weightMatrix, nextLayer.errorVector)

        # Apply sigmoid' to currLayer.zVector in place
        for i in range(self.Layers[layerIdx].size):
            currLayer.zVector[i] = sigmoidDeriv(currLayer.zVector[i])

        # sigmoid' was applied to self.Layers[self.Layers.size - 1].zVector in place
        # TODO: Maybe we can calculate sigmoid' to a temporary vector
        currLayer.errorVector = np.multiply(weightTimesError, currLayer.zVector)

    # All of this would be MUCH easier if W and B were stored as matrices and vectors
    def adjustBasedOnGradientDescentForCurrentExample(self, learningRate, numberInBatch):
        print("5) Gradient Descent")

        npm = learningRate / numberInBatch

        # Adjust biases
        layerIdx = 3
        for i in range(self.Layers[layerIdx].size):
            self.Layers[layerIdx].neurons[i].bias -= npm * self.Layers[layerIdx].errorVector[i]
        layerIdx = 2
        for i in range(self.Layers[layerIdx].size):
            self.Layers[layerIdx].neurons[i].bias -= npm * self.Layers[layerIdx].errorVector[i]
        layerIdx = 1
        for i in range(self.Layers[layerIdx].size):
            self.Layers[layerIdx].neurons[i].bias -= npm * self.Layers[layerIdx].errorVector[i]

        # Adjust weights
        layerIdx = 3
        for nIdx in range(self.Layers[layerIdx].size):
            for wIdx in range(self.Layers[layerIdx].neurons[nIdx].incomingWeights.size):
                self.Layers[layerIdx].neurons[nIdx].incomingWeights[wIdx] -= npm * self.Layers[layerIdx].errorVector[i] * self.Layers[layerIdx - 1].neurons[wIdx].activation
        layerIdx = 2
        for nIdx in range(self.Layers[layerIdx].size):
            for wIdx in range(self.Layers[layerIdx].neurons[nIdx].incomingWeights.size):
                self.Layers[layerIdx].neurons[nIdx].incomingWeights[wIdx] -= npm * self.Layers[layerIdx].errorVector[i] * self.Layers[layerIdx - 1].neurons[wIdx].activation
        layerIdx = 1
        for nIdx in range(self.Layers[layerIdx].size):
            for wIdx in range(self.Layers[layerIdx].neurons[nIdx].incomingWeights.size):
                self.Layers[layerIdx].neurons[nIdx].incomingWeights[wIdx] -= npm * self.Layers[layerIdx].errorVector[i] * self.Layers[layerIdx - 1].neurons[wIdx].activation
        
    def coutBase(self):
        for i in range(self.Matrices.size):
            self.Layers[i].coutBase()
            print()
            self.Matrices[i].cout()
            print()

        self.Layers[self.Layers.size - 1].coutBase()

    def cout(self):
        for i in range(self.Matrices.size):
            self.Layers[i].cout()
            print()
            self.Matrices[i].cout()
            print()

        self.Layers[self.Layers.size - 1].cout()

In [85]:
# MNIST Dataset: 28 x 28 = 784
import pickle

#net = Network(784, 16, 16, 10)
net = Network(4, 3, 3, 2)

#with open("dataset/pickled/first_10_data_train.pickle", "rb") as infile:
#    data_batch = pickle.load(infile)
#with open("dataset/pickled/first_10_label_train.pickle", "rb") as infile:
#    label_batch = pickle.load(infile)

#with open("network.pickle", "rb") as infile:
#   net = pickle.load(infile)

net.coutBase()
net.fullForwardPropagation(1)
net.coutBase()
net.fullBackwardPropagation(1)
net.cout()
# net.adjustBasedOnGradientDescentForCurrentExample(1, 1)
# net.coutBase()

#with open("network.pickle", "wb") as outfile:
#    pickle.dump(net, outfile)

Activations: 
[0.63812718 0.37727305 0.30067157 0.47212682]
Biases: 
[0.61285521 0.33100534 0.64583    0.45346297]

[[0.53868438 0.3076507  0.75736853 0.69632286]
 [0.68977026 0.71179891 0.22317052 0.28986183]
 [0.02492046 0.60822664 0.65642905 0.65217316]]

Activations: 
[0.0480375  0.07219713 0.9777653 ]
Biases: 
[0.91568093 0.10384257 0.30362663]

[[0.55312102 0.54126127 0.17085934]
 [0.20869274 0.33995442 0.87352611]
 [0.03462209 0.09109957 0.07698062]]

Activations: 
[0.29231249 0.03376021 0.75274579]
Biases: 
[0.31443663 0.11240763 0.55300343]

[[0.56844171 0.92113935 0.72169758]
 [0.24560663 0.27240178 0.4380934 ]]

Activations: 
[0.49997205 0.70861789]
Biases: 
[0.96829497 0.20958697]
2) Feedforward: Compute all activations for all layers
Target is: 1
Cost is: 0.23755050849900627
Activations: 
[0.63812718 0.37727305 0.30067157 0.47212682]
Biases: 
[0.61285521 0.33100534 0.64583    0.45346297]

[[0.53868438 0.3076507  0.75736853 0.69632286]
 [0.68977026 0.71179891 0.22317052 0.2

AttributeError: 'weightMatrix' object has no attribute 'transpose'