In [1]:
import random as random
import numpy as np

class Layer:
    def __init__(self, currentLayerLen):
        self.activationVector = np.array([random.uniform(0, 1) for i in range(currentLayerLen)])
        self.biasVector = np.array([random.uniform(0, 1) for i in range(currentLayerLen)])
        self.adjBiasVector = np.zeros(currentLayerLen)
        self.zVector = np.zeros(shape = (currentLayerLen, 1))
        self.errorVector = np.zeros(shape = (currentLayerLen, 1))
        self.size = currentLayerLen

    def resetAdjBiasVector(self):
        self.adjBiasVector = np.zeros(self.biasVector.size)

    def cout(self):
        print("Activations: ")
        print(self.activationVector)
        print("Biases: ")
        print(self.biasVector)
        print("Z Vector: ")
        print(self.zVector)
        print("Error: ")
        print(self.errorVector)

    def coutBase(self):
        print("Activations: ")
        print(self.activationVector)
        print("Biases: ")
        print(self.biasVector)

In [2]:
class weightMatrix:
    def __init__(self, prevLayerLen, nextLayerLen):
        self.matrix = np.random.rand(nextLayerLen, prevLayerLen)
        self.adjMatrix = np.zeros((nextLayerLen, prevLayerLen))

    def resetAdjMatrix(self):
        self.adjMatrix = np.zeros((self.matrix.shape))

    def cout(self):
        print(self.matrix)

In [ ]:
def sigmoid(x):
    if (abs(x) > 500):
        return 0
    return 1 / (1 + np.exp(-x))

def sigmoidDeriv(x):
    if (abs(x) > 500):
        return 1
    return np.exp(-x) / ((1 + np.exp(-x)) * (1 + np.exp(-x)))

class Network:

    def __init__(self, start, first, second, end):
        startLayer = Layer(start)
        firstLayer = Layer(first)
        secondLayer = Layer(second)
        endLayer = Layer(end)

        self.Layers = np.array([startLayer, firstLayer, secondLayer, endLayer])

        firstMatrix = weightMatrix(start, first)
        secondMatrix = weightMatrix(first, second)
        endMatrix = weightMatrix(second, end)

        # Indexed with the layer before the matrix
        self.Matrices = np.array([firstMatrix, secondMatrix, endMatrix])

    def calculateZVector(self, layerIdx):
        # self.Layers[layerIdx - 1] is previous Layer
        # currLayer = self.Layers[layerIdx] is current Layer
        # self.Matrices[layerIdx - 1].matrix is weight matrix related to this calculation
        # self.Layers[layerIdx - 1].activationVector is previous activation
        # self.Layers[layerIdx].biasVector is current Bias

        # Weight matrix * previous activation vector
        self.Layers[layerIdx].zVector = np.dot(self.Matrices[layerIdx - 1].matrix, self.Layers[layerIdx - 1].activationVector)
        # += current bias vector
        self.Layers[layerIdx].zVector += self.Layers[layerIdx].biasVector

    def forwardPropagationStep(self, layerIdx):
        # currLayer = self.Layers[layerIdx] is current Layer

        self.calculateZVector(layerIdx)

        for i in range(self.Layers[layerIdx].size):
            self.Layers[layerIdx].activationVector[i] = sigmoid(self.Layers[layerIdx].zVector[i])

    # Assumes that data is between 0 and 255 value
    def setStartLayerActivations(self, dataset):
        # FOR test

        for idx in range(0, 4):
            self.Layers[0].activationVector[idx] = dataset[idx]

        # #
        # # FOR MINST
        # #

        # # self.Layers[0] is start Layer

        # if len(dataset) * len(dataset[0]) != self.Layers[0].size:
        #     print("There is a mismatch between the size of the input data and the start layer!")
        #     print("Size of dataset is: " + str(len(dataset) * len(dataset[0])))
        #     print("Size of first layer is: " + str(self.Layers[0].size))

        # #print("1) Set the activations of the first layer")

        # layerIdx = 0
        # for row in range(0, len(dataset)):
        #     for col in range(0, len(dataset[0])):
        #         self.Layers[0].activationVector[layerIdx] = dataset[row][col] / 255
        #         layerIdx += 1

    def fullForwardPropagation(self, target):
        #print("2) Feedforward: Compute all activations for all layers")
        self.forwardPropagationStep(1)
        self.forwardPropagationStep(2)
        self.forwardPropagationStep(3)

        #print("Target is: " + str(target))
        #print("Cost is: " + str(self.cost(target)))
    
    def cost(self, target):
        # self.Layers[self.Layers.size - 1] is end Layer

        sum = 0

        for i in range(self.Layers[self.Layers.size - 1].size):
            if (i == target):
                sum += pow(self.Layers[self.Layers.size - 1].activationVector[i] - 1.0, 2)
            else:
                sum += pow(self.Layers[self.Layers.size - 1].activationVector[i], 2)
        return sum / (2 * self.Layers[self.Layers.size - 1].size)
    
    def fullBackwardPropagation(self, target):
        #print("3) Output Error in last layer")
        self.calculateErrorInLastLayerForTarget(target)
        self.cout("\n\n ----- \n\n")

        #print("4) Backpropagate error: calculate error for all layers")
        self.calculateErrorFromNextLayerError(2)
        self.cout("\n\n ----- \n\n")
        self.calculateErrorFromNextLayerError(1)
        self.cout("\n\n ----- \n\n")
    
    # The cost function is hard coded
    def calculateErrorInLastLayerForTarget(self, target):
        # self.Layers[self.Layers.size - 1] is end Layer

        CGradient = self.Layers[self.Layers.size - 1].activationVector
        # The desired value for target is 1
        # This subtracts from the activations[target] as well !
        # The change of the activations shouldnt matter
        # It is not used later in the algo for the training example
        CGradient[target] -= 1.0

        # Apply sigmoid' to endLayer.zVector in place
        for i in range(self.Layers[self.Layers.size - 1].size):
            self.Layers[self.Layers.size - 1].zVector[i] = sigmoidDeriv(self.Layers[self.Layers.size - 1].zVector[i])

        # sigmoid' was applied to endLayer.zVector in place
        self.Layers[self.Layers.size - 1].errorVector = np.multiply(CGradient, self.Layers[self.Layers.size - 1].zVector)

    # Assumes error in next layer is up to date
    def calculateErrorFromNextLayerError(self, layerIdx):
        # self.Layers[layerIdx] is current Layer
        # self.Layers[layerIdx + 1] is next Layer

        # self.Matrices[layerIdx].matrix.transpose() is the transposed weight matrix
        # np.dot(transposedWeightMatrix, self.Layers[layerIdx + 1].errorVector) is transposed weight matrix * next layer error

        # Apply sigmoid' to currLayer.zVector in place
        for i in range(self.Layers[layerIdx].size):
            self.Layers[layerIdx].zVector[i] = sigmoidDeriv(self.Layers[layerIdx].zVector[i])

        # sigmoid' was applied to self.Layers[self.Layers.size - 1].zVector in place
        # error = (transposed weight matrix * next layer error) o sigmoid'(z)
        # Where o is index by index multiplication
        self.Layers[layerIdx].errorVector = np.multiply(np.dot(self.Matrices[layerIdx].matrix.transpose(), self.Layers[layerIdx + 1].errorVector), self.Layers[layerIdx].zVector)

    # All of this would be MUCH easier if W and B were stored as matrices and vectors
    def adjustBasedOnGradientDescentForCurrentExample(self, learningRate, numberInBatch):
        #print("5) Gradient Descent")

        # npm stands for n per m
        # where: n: learning rate
        #        m: number of train examples in batch
        npm = learningRate / numberInBatch

        # Adjust biases
        for layerIdx in range(1, self.Layers.size):
            # self.Layers[layerIdx] is current Layer

            #self.Layers[layerIdx].biasVector -= npm * self.Layers[layerIdx].errorVector
            #print("Delta is (bias): ", -npm * self.Layers[layerIdx].errorVector)

            self.Layers[layerIdx].adjBiasVector += npm * self.Layers[layerIdx].errorVector

        # # Adjust weights
        for weightMatrixIdx in range(self.Matrices.size):
            # self.Matrices[weightMatrixIdx].matrix is current weight matrix
            # self.Layers[weightMatrixIdx + 1] is current Layer
            # self.Layers[weightMatrixIdx] is previous Layer

            # For matrix mupltiplications the vectors need to be 2D
            # This is how we make them 2D
            # np.array([self.Layers[weightMatrixIdx].activationVector]) is previous activations
            # np.array([self.Layers[weightMatrixIdx + 1].errorVector]) is current error
            # Temp variable to make code more understandable
            
            # weight matrix -= (current Error)T * previous activation
            #self.Matrices[weightMatrixIdx].matrix -= npm * np.dot(np.array([self.Layers[weightMatrixIdx + 1].errorVector]).transpose(), np.array([self.Layers[weightMatrixIdx].activationVector]))
            #print("Delta is (weight): ", -npm * np.dot(np.array([self.Layers[weightMatrixIdx + 1].errorVector]).transpose(), np.array([self.Layers[weightMatrixIdx].activationVector])))

            self.Matrices[weightMatrixIdx].adjMatrix += npm * np.dot(np.array([self.Layers[weightMatrixIdx + 1].errorVector]).transpose(), np.array([self.Layers[weightMatrixIdx].activationVector]))

    def clearAdjustVariables(self):
        for layer in self.Layers:
            layer.resetAdjBiasVector()

        for matrix in self.Matrices:
            matrix.resetAdjMatrix()

    def adjustWithAdjustVariables(self):
        for layerIdx in range(1, self.Layers.size):
            self.Layers[layerIdx].biasVector -= self.Layers[layerIdx].adjBiasVector

        for weightMatrixIdx in range(self.Matrices.size):
            self.Matrices[weightMatrixIdx].matrix -= self.Matrices[weightMatrixIdx].adjMatrix

    def trainBatch(self, data, labels, learningRate):
        # Check if there is a length mismatch
        if (len(data) != len(labels)):
            print("There is a mismatch between the length of the data and lables")
            print("Length of data is: " + str(data.size))
            print("Length of labels are: " + str(labels.size))

        self.clearAdjustVariables()

        numberInBatch = len(data)

        for idx in range(numberInBatch):
            # Steps of one training 
            print("\n\n------------------ Set start layer activations ------------------\n\n")
            self.setStartLayerActivations(data[idx])
            self.cout()
            print("\n\n------------------ Full forward propagation ------------------\n\n")
            self.fullForwardPropagation(labels[idx])
            self.cout()
            print("\n\n------------------ Full backward propagation ------------------\n\n")
            self.fullBackwardPropagation(labels[idx])
            print("\n\n------------------ Adjust based on gradient descent for current example ------------------\n\n")
            self.adjustBasedOnGradientDescentForCurrentExample(learningRate, numberInBatch)
            self.cout()

        self.adjustWithAdjustVariables()

    def findPrediction(self):
        endLayerActivations = self.Layers[3].activationVector

        max = 0
        maxIdx = 11

        for idx in range(endLayerActivations.size):
            if endLayerActivations[idx] > max:
                max = endLayerActivations[idx]
                maxIdx = idx

        return maxIdx

    def test(self, data, labels):
        # Check if there is a length mismatch
        if (len(data) != len(labels)):
            print("There is a mismatch between the length of the data and lables")
            print("Length of data is: " + str(data.size))
            print("Length of labels are: " + str(labels.size))

        # Test for percentage of correct classifications
        # numberOfTest = len(data)
        # correct = 0

        # for idx in range(numberOfTest):
        #     self.setStartLayerActivations(data[idx])
        #     self.fullForwardPropagation(labels[idx])

        #     correctIdx = self.findPrediction()

        #     if correctIdx == labels[idx]:
        #         correct += 1

        # return correct/numberOfTest

        numberOfTest = len(data)
        sumCost = 0
        correct = 0

        for idx in range(numberOfTest):
            self.setStartLayerActivations(data[idx])
            self.fullForwardPropagation(labels[idx])

            sumCost += self.cost(labels[idx])

            correctIdx = self.findPrediction()
            if correctIdx == labels[idx]:
                correct += 1

        print("Average cost is: ", sumCost / numberOfTest)
        print("Percentage of correct is: ", correct / numberOfTest)

    def coutActivation(self):
        for idx in range(self.Layers.size):
            print("Layer: " + str(idx))
            print(self.Layers[idx].activationVector)

    def coutBase(self):
        for i in range(self.Matrices.size):
            print("Layer: ", i)
            self.Layers[i].coutBase()
            print()
            self.Matrices[i].cout()
            print()

        print("Layer: ", self.Layers.size - 1)
        self.Layers[self.Layers.size - 1].coutBase()

    def cout(self):
        for i in range(self.Matrices.size):
            print("Layer: ", i)
            self.Layers[i].cout()
            print()
            self.Matrices[i].cout()
            print()

        print("Layer: ", self.Layers.size - 1)
        self.Layers[self.Layers.size - 1].cout()

In [4]:
# MNIST Dataset: 28 x 28 = 784
import pickle

# with open("network.pickle", "rb") as infile:
#     net = pickle.load(infile)

net = Network(4, 3, 3, 2)
#net = Network(784, 16, 16, 10)

# Network is loaded into net

training = True
testing = False

if training:
    #
    # 4 3 3 2 Test run
    #

    dummyData = [[0.125, 0.25, 0.675, 0.885]]
    dummyLabel = [0]

    net.trainBatch(dummyData, dummyLabel, 100)

    # #
    # # Training on the actual data
    # #

    # with open("dataset/pickled/data_batch_01.pickle", "rb") as infile:
    #     data_batch_01 = pickle.load(infile)
    # with open("dataset/pickled/label_batch_01.pickle", "rb") as infile:
    #     label_batch_01 = pickle.load(infile)
    # # with open("dataset/pickled/data_batch_02.pickle", "rb") as infile:
    # #     data_batch_02 = pickle.load(infile)
    # # with open("dataset/pickled/label_batch_02.pickle", "rb") as infile:
    # #     label_batch_02 = pickle.load(infile)
    # # with open("dataset/pickled/data_batch_03.pickle", "rb") as infile:
    # #     data_batch_03 = pickle.load(infile)
    # # with open("dataset/pickled/label_batch_03.pickle", "rb") as infile:
    # #     label_batch_03 = pickle.load(infile)
    # # with open("dataset/pickled/data_batch_04.pickle", "rb") as infile:
    # #     data_batch_04 = pickle.load(infile)
    # # with open("dataset/pickled/label_batch_04.pickle", "rb") as infile:
    # #     label_batch_04 = pickle.load(infile)
    # # with open("dataset/pickled/data_batch_05.pickle", "rb") as infile:
    # #     data_batch_05 = pickle.load(infile)
    # # with open("dataset/pickled/label_batch_05.pickle", "rb") as infile:
    # #     label_batch_05 = pickle.load(infile)

    # # with open("dataset/pickled/data_batch_first_100.pickle", "rb") as infile:
    # #     data_batch_first_100 = pickle.load(infile)
    # # with open("dataset/pickled/label_batch_first_100.pickle", "rb") as infile:
    # #     label_batch_first_100 = pickle.load(infile)

    # with open("dataset/pickled/data_test.pickle", "rb") as infile:
    #     data_test = pickle.load(infile)
    # with open("dataset/pickled/label_test.pickle", "rb") as infile:
    #     label_test = pickle.load(infile)

    # print("Testing on batch data:")
    # net.test(data_batch_01, label_batch_01)
    # print("Testing on test data:")
    # net.test(data_test, label_test)

    # print("Testing on the batch")
    # for i in range(1000):
    #     net.trainBatch(data_batch_01, label_batch_01, 1000)
    #     net.test(data_batch_01, label_batch_01)
    #     #net.test(data_test, label_test)

    # print("Testing on batch data:")
    # net.test(data_batch_01, label_batch_01)
    # print("Testing on test data:")
    # net.test(data_test, label_test)

    # with open("network.pickle", "wb") as outfile:
    #     pickle.dump(net, outfile)

if testing:
    with open("dataset/pickled/data_test.pickle", "rb") as infile:
        data_test = pickle.load(infile)
    with open("dataset/pickled/label_test.pickle", "rb") as infile:
        label_test = pickle.load(infile)

    #print("Percentage of correct is: " + str(net.test(data_test, label_test)))
    net.test(data_test, label_test)



------------------ Set start layer activations ------------------


Layer:  0
Activations: 
[0.125 0.25  0.675 0.885]
Biases: 
[0.81017369 0.79850249 0.21358366 0.75343774]
Z Vector: 
[[0.]
 [0.]
 [0.]
 [0.]]
Error: 
[[0.]
 [0.]
 [0.]
 [0.]]

[[0.2186861  0.05628616 0.50158869 0.07855625]
 [0.24375452 0.97271557 0.1624343  0.15810173]
 [0.58186105 0.73510785 0.2521241  0.28141627]]

Layer:  1
Activations: 
[0.79907755 0.93657437 0.30411115]
Biases: 
[0.65877022 0.31752805 0.54370358]
Z Vector: 
[[0.]
 [0.]
 [0.]]
Error: 
[[0.]
 [0.]
 [0.]]

[[0.3343155  0.09066698 0.39867784]
 [0.47740735 0.72693575 0.00087981]
 [0.32778366 0.23349489 0.81914665]]

Layer:  2
Activations: 
[0.02441467 0.57682694 0.42887925]
Biases: 
[0.70919512 0.55997546 0.34556808]
Z Vector: 
[[0.]
 [0.]
 [0.]]
Error: 
[[0.]
 [0.]
 [0.]]

[[0.53792913 0.26647645 0.82172938]
 [0.04437043 0.1676009  0.18768672]]

Layer:  3
Activations: 
[0.39815912 0.25884777]
Biases: 
[0.46764252 0.39521433]
Z Vector: 
[[0.]
 [0.]]
E